spring:
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  application:
    name: conversionfactor
  h2:
    console:
      enabled: true
      path: /h2
      
server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
     defaultZone: http://104.198.194.127:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
