--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: conversionFactor
    version: v1
  name: conversionFactor
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: conversionFactor
      version: v1
  template: 
    metadata: 
      labels: 
        app: conversionFactor
        version: v1

    spec: 

      containers: 
        - 
          image: "ithulasi/conversionfactor0106:1"
          imagePullPolicy: Always
          name: conversionFactor
          env:
            - name: conversionFactor.eureka.url
              value: "http://eureka:8761/eureka"  

              
                    
