--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: conversionfactor0206
    version: v1
  name: conversionfactor0206
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: conversionfactor0206
      version: v1
  template: 
    metadata: 
      labels: 
        app: conversionfactor0206
        version: v1

    spec: 

      containers: 
        - 
          image: "ithulasi/conversionfactor0106:1"
          imagePullPolicy: Always
          name: conversionfactor0206
          ports: 
#          - containerPort: 8081   
          - name: httpport
            containerPort: 8083
            hostPort: 8083
          env:
            - name: conversionfactor0206.eureka.url
              value: "http://eureka:8761/eureka"  
